mysqldump4archive - (fetch; compress&)
run compression in parallel with subsequent dump;
chmod is postponed, and tolerant of omitting the mk-table-checksum part

diff --git a/bin/mysqldump4archive b/bin/mysqldump4archive
--- a/bin/mysqldump4archive
+++ b/bin/mysqldump4archive
@@ -1,4 +1,5 @@
-#! /bin/sh
+#! /bin/bash
+# bash for fancy job control
 
 # It started off as a quick hack script...
 #
@@ -18,15 +19,58 @@ DBLIST=$*
 : ${dbpass:=""}
 
 : ${OUTDIR:=.}
-: ${BZIP:=pbzip2}
+: ${BZIP:=pbzip2 -l -9}
 
 
 set -e
+set -m
 echo "Will archive for each FOO in ($DBLIST) to $OUTDIR/FOO.*"
 
+job_mopup() {
+    local jobrun jobwhat joberr
+
+    jobrun="$( jobs -lr  | sed -e 's/^/  /' )"
+    if [ -n "$jobrun" ]; then
+        printf "  jobs are running, wait...\n%s\n" "$jobrun"
+    fi
+
+    echo "  job cleanup"
+    for j in $( jobs | perl -ne 'print " \%$1 " if m{^\s*\[(\d+)\]}' ); do
+        jobwhat="$( jobs -l $j )"
+        echo "    fg $j : $jobwhat"
+        if wait $j; then
+            echo "      OK"
+        else
+            joberr=$?
+            printf "job %s (%s) failed: %s\n" $j "$jobwhat" $joberr >&2
+            exit $joberr
+        fi
+    done
+}
+
+main() {
 # set -x
-for dbinst in $DBLIST; do
-    echo "Archive $dbinst into $dbinst.{sql.bz2,log,sql.md5,tmd5}"
+    for dbinst in $DBLIST; do
+        echo "Archive $dbinst into $dbinst.{sql.bz2,log,sql.md5,tmd5}"
+
+        if [ -s "$OUTDIR/$dbinst.sql.bz2" ]; then
+            echo "  Already dumped"
+            ls -lhrt "$OUTDIR/$dbinst".* | sed -e 's/^/    /'
+        else
+            do_dump $dbinst
+        fi
+    done
+
+    job_mopup
+
+    for dbinst in $DBLIST; do
+        chmod -c a-w $OUTDIR/$dbinst.*
+    done
+}
+
+do_dump() {
+    local dbinst
+    dbinst="$1"
 
     echo "  dumping..."
     mysqldump -h$dbhost -P$dbport -u$dbuser -p$dbpass \
@@ -34,17 +78,18 @@ for dbinst in $DBLIST; do
 	--log-error $dbinst.log \
 	--databases $dbinst | tee $OUTDIR/$dbinst.sql | md5sum | perl -pe 'BEGIN { $fn=shift } s/  -$/  $fn/' $dbinst.sql > $OUTDIR/$dbinst.sql.md5
 
-    echo "  mk-table-checksum..."
-    ssh deskpro \
-	mk-table-checksum --algorithm BIT_XOR --chunksize 50000 -d $dbinst h=$dbhost,P=$dbport,u=$dbuser,p=$dbpass > $OUTDIR/$dbinst.tmd5
+#    echo "  mk-table-checksum..."
+#    ssh deskpro \
+#	mk-table-checksum --algorithm BIT_XOR --chunksize 50000 -d $dbinst h=$dbhost,P=$dbport,u=$dbuser,p=$dbpass > $OUTDIR/$dbinst.tmd5
     # it's not installed on cbi4, perhaps should be
 
-    echo "  compress..."
-    $BZIP -v9 $OUTDIR/$dbinst.sql
+    job_mopup
 
-    chmod a-w $OUTDIR/$dbinst.{sql.bz2,sql.md5,tmd5}
-done
+    $BZIP $OUTDIR/$dbinst.sql &
+    echo "  started compression $OUTDIR/$dbinst.sql on pid $!"
+}
 
+main "$@"
 
 # Checking compressed files (bash oneliner)
 #
